// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class ActivityStatus
    {
        public ActivityStatus()
        {
            Activities = new HashSet<Activity>();
        }

        public int ActivityStatusId { get; set; }
        public string ActivityStatusDescription { get; set; }

        public virtual ICollection<Activity> Activities { get; set; }
    }
}