// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class ActivityCategory
    {
        public ActivityCategory()
        {
            Activities = new HashSet<Activity>();
        }

        [Key]
        public int ActivityCategoryId { get; set; }
        [Required]
        [StringLength(50)]
        public string ActivityCategoryName { get; set; }

        [InverseProperty("fk_ActivityCategory")]
        public virtual ICollection<Activity> Activities { get; set; }
    }
}