// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    [Table("ActivityImg")]
    public partial class ActivityImg
    {
        [Key]
        public int Id { get; set; }
        public int fk_ActivityId { get; set; }
        [Required]
        [StringLength(300)]
        public string ImgPath { get; set; }

        [ForeignKey("fk_ActivityId")]
        [InverseProperty("ActivityImgs")]
        public virtual Activity fk_Activity { get; set; }
    }
}