// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class Article
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public DateTime? PublishTime { get; set; }
        public string Author { get; set; }
    }
}