// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    [Index("BranchName", Name = "UQ__Branches__3903DB0396AE7A84", IsUnique = true)]
    [Index("BranchAddress", Name = "UQ__Branches__F50DE17ADEB4A600", IsUnique = true)]
    public partial class Branch
    {
        public Branch()
        {
            OneToOneReservations = new HashSet<OneToOneReservation>();
            Speakers = new HashSet<Speaker>();
        }

        [Key]
        public int BranchId { get; set; }
        [Required]
        [StringLength(50)]
        public string BranchName { get; set; }
        [Required]
        [StringLength(100)]
        public string BranchAddress { get; set; }

        [InverseProperty("fk_Branch")]
        public virtual ICollection<OneToOneReservation> OneToOneReservations { get; set; }
        [InverseProperty("fk_SpeakerBranch")]
        public virtual ICollection<Speaker> Speakers { get; set; }
    }
}