// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class CartItem
    {
        public int CartItemId { get; set; }
        public int fk_CardId { get; set; }
        public int fk_ProductId { get; set; }
        public string Description { get; set; }
        public int Qty { get; set; }

        public virtual ShoppingCart fk_Card { get; set; }
        public virtual ProductGroup fk_Product { get; set; }
    }
}