// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class ColorCategory
    {
        public ColorCategory()
        {
            ProductGroups = new HashSet<ProductGroup>();
            ProductImgs = new HashSet<ProductImg>();
        }

        [Key]
        public int ColorId { get; set; }
        [Required]
        [StringLength(50)]
        public string ColorName { get; set; }

        [InverseProperty("fk_Color")]
        public virtual ICollection<ProductGroup> ProductGroups { get; set; }
        [InverseProperty("fk_Color")]
        public virtual ICollection<ProductImg> ProductImgs { get; set; }
    }
}