// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class CouponSending
    {
        [Key]
        public int SendingId { get; set; }
        public int fk_CouponId { get; set; }
        public int? fk_MemberId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime SentDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        public bool RedemptionStatus { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RedeemedDate { get; set; }

        [ForeignKey("fk_CouponId")]
        [InverseProperty("CouponSendings")]
        public virtual Coupon fk_Coupon { get; set; }
        [ForeignKey("fk_MemberId")]
        [InverseProperty("CouponSendings")]
        public virtual Member fk_Member { get; set; }
    }
}