// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class CouponCategory
    {
        public CouponCategory()
        {
            Coupons = new HashSet<Coupon>();
        }

        [Key]
        public int CouponCategoryId { get; set; }
        [Required]
        [StringLength(20)]
        public string CouponCategoryName { get; set; }

        [InverseProperty("fk_CouponCategory")]
        public virtual ICollection<Coupon> Coupons { get; set; }
    }
}