// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class CouponCategory
    {
        public CouponCategory()
        {
            Coupons = new HashSet<Coupon>();
        }

        public int CouponCategoryId { get; set; }
        public string CouponCategoryName { get; set; }

        public virtual ICollection<Coupon> Coupons { get; set; }
    }
}