// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class CustomizedOrder
    {
        [Key]
        public int Customized_Id { get; set; }
        [Required]
        [StringLength(6000)]
        [Unicode(false)]
        public string Customized_number { get; set; }
        public int? Customized_Shoes_Id { get; set; }
        public int? Fk_ForMemberCustomized_Id { get; set; }
        public int? Customized_Eyelet { get; set; }
        public int? Customized_EdgeProtection { get; set; }
        public int? Customized_Rear { get; set; }
        public int? Customized_Tongue { get; set; }
        public int? Customized_Toe { get; set; }
        [StringLength(254)]
        public string Remark { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OrderCreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OrderEditTime { get; set; }

        [ForeignKey("Customized_EdgeProtection")]
        [InverseProperty("CustomizedOrderCustomized_EdgeProtectionNavigations")]
        public virtual Customized_material Customized_EdgeProtectionNavigation { get; set; }
        [ForeignKey("Customized_Eyelet")]
        [InverseProperty("CustomizedOrderCustomized_EyeletNavigations")]
        public virtual Customized_material Customized_EyeletNavigation { get; set; }
        [ForeignKey("Customized_Rear")]
        [InverseProperty("CustomizedOrderCustomized_RearNavigations")]
        public virtual Customized_material Customized_RearNavigation { get; set; }
        [ForeignKey("Customized_Shoes_Id")]
        [InverseProperty("CustomizedOrders")]
        public virtual CustomizedShoesPo Customized_Shoes { get; set; }
        [ForeignKey("Customized_Toe")]
        [InverseProperty("CustomizedOrderCustomized_ToeNavigations")]
        public virtual Customized_material Customized_ToeNavigation { get; set; }
        [ForeignKey("Customized_Tongue")]
        [InverseProperty("CustomizedOrderCustomized_TongueNavigations")]
        public virtual Customized_material Customized_TongueNavigation { get; set; }
        [ForeignKey("Fk_ForMemberCustomized_Id")]
        [InverseProperty("CustomizedOrders")]
        public virtual Member Fk_ForMemberCustomized { get; set; }
    }
}