// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class CustomizedShoesPo
    {
        public CustomizedShoesPo()
        {
            CustomizedOrders = new HashSet<CustomizedOrder>();
            ShoesGroups = new HashSet<ShoesGroup>();
            ShoesPictures = new HashSet<ShoesPicture>();
        }

        public int ShoesProductId { get; set; }
        public string ShoesName { get; set; }
        public string ShoesDescription { get; set; }
        public string ShoesOrigin { get; set; }
        public int ShoesUnitPrice { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public bool? Status { get; set; }
        public int? fk_ShoesCategoryId { get; set; }
        public int? fk_ShoesColorId { get; set; }
        public DateTime DataCreateTime { get; set; }
        public DateTime DataEditTime { get; set; }

        public virtual ShoesCategory fk_ShoesCategory { get; set; }
        public virtual ShoesColorCategory fk_ShoesColor { get; set; }
        public virtual ICollection<CustomizedOrder> CustomizedOrders { get; set; }
        public virtual ICollection<ShoesGroup> ShoesGroups { get; set; }
        public virtual ICollection<ShoesPicture> ShoesPictures { get; set; }
    }
}