// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class Customized_material
    {
        public Customized_material()
        {
            CustomizedOrderCustomized_EdgeProtectionNavigations = new HashSet<CustomizedOrder>();
            CustomizedOrderCustomized_EyeletNavigations = new HashSet<CustomizedOrder>();
            CustomizedOrderCustomized_RearNavigations = new HashSet<CustomizedOrder>();
            CustomizedOrderCustomized_ToeNavigations = new HashSet<CustomizedOrder>();
            CustomizedOrderCustomized_TongueNavigations = new HashSet<CustomizedOrder>();
            ShoesGroups = new HashSet<ShoesGroup>();
        }

        [Key]
        public int Shoesmaterial_Id { get; set; }
        [Required]
        [StringLength(50)]
        public string material_Name { get; set; }

        [InverseProperty("Customized_EdgeProtectionNavigation")]
        public virtual ICollection<CustomizedOrder> CustomizedOrderCustomized_EdgeProtectionNavigations { get; set; }
        [InverseProperty("Customized_EyeletNavigation")]
        public virtual ICollection<CustomizedOrder> CustomizedOrderCustomized_EyeletNavigations { get; set; }
        [InverseProperty("Customized_RearNavigation")]
        public virtual ICollection<CustomizedOrder> CustomizedOrderCustomized_RearNavigations { get; set; }
        [InverseProperty("Customized_ToeNavigation")]
        public virtual ICollection<CustomizedOrder> CustomizedOrderCustomized_ToeNavigations { get; set; }
        [InverseProperty("Customized_TongueNavigation")]
        public virtual ICollection<CustomizedOrder> CustomizedOrderCustomized_TongueNavigations { get; set; }
        [InverseProperty("fk_Material")]
        public virtual ICollection<ShoesGroup> ShoesGroups { get; set; }
    }
}