// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class Department
    {
        public Department()
        {
            Staff = new HashSet<Staff>();
        }

        [Key]
        public int DepartmentId { get; set; }
        [StringLength(50)]
        public string DepartmentName { get; set; }

        [InverseProperty("fk_Department")]
        public virtual ICollection<Staff> Staff { get; set; }
    }
}