// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class Discount
    {
        [Key]
        public int DiscountId { get; set; }
        [Required]
        [StringLength(20)]
        public string DiscountName { get; set; }
        [StringLength(100)]
        public string DiscountDescription { get; set; }
        public int? fk_ProjectTagId { get; set; }
        public int DiscountType { get; set; }
        public int DiscountValue { get; set; }
        public int ConditionType { get; set; }
        public int ConditionValue { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        public int? OrderBy { get; set; }
        public bool? Status { get; set; }

        [ForeignKey("fk_ProjectTagId")]
        [InverseProperty("Discounts")]
        public virtual ProjectTag fk_ProjectTag { get; set; }
    }
}