// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class JobTitle
    {
        public JobTitle()
        {
            Staff = new HashSet<Staff>();
        }

        public int TitleId { get; set; }
        public string TitleName { get; set; }
        public int? fk_StaffPermissions { get; set; }

        public virtual ICollection<Staff> Staff { get; set; }
    }
}