// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    [Index("Mobile", Name = "UQ__Members__6FAE0782E1A56EB7", IsUnique = true)]
    [Index("Email", Name = "UQ__Members__A9D1053442354E1D", IsUnique = true)]
    [Index("Account", Name = "UQ__Members__B0C3AC46ED2152FF", IsUnique = true)]
    public partial class Member
    {
        public Member()
        {
            CouponSendings = new HashSet<CouponSending>();
            CustomizedOrders = new HashSet<CustomizedOrder>();
            OneToOneReservations = new HashSet<OneToOneReservation>();
            PointHistories = new HashSet<PointHistory>();
            PointTradeIns = new HashSet<PointTradeIn>();
            ShoppingCarts = new HashSet<ShoppingCart>();
            orders = new HashSet<order>();
        }

        [Key]
        public int MemberId { get; set; }
        [Required]
        [StringLength(30)]
        public string Name { get; set; }
        public byte? Age { get; set; }
        public bool? Gender { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string Mobile { get; set; }
        [Required]
        [StringLength(300)]
        public string Email { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Birthday { get; set; }
        [StringLength(100)]
        public string CommonAddress { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string Account { get; set; }
        [Required]
        [StringLength(70)]
        [Unicode(false)]
        public string EncryptedPassword { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Registration { get; set; }
        public bool? IsConfirmed { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ConfirmCode { get; set; }
        public bool? IsSubscribeNews { get; set; }
        public int fk_LevelId { get; set; }
        public int? fk_BlackListId { get; set; }

        [ForeignKey("fk_BlackListId")]
        [InverseProperty("Members")]
        public virtual BlackList fk_BlackList { get; set; }
        [ForeignKey("fk_LevelId")]
        [InverseProperty("Members")]
        public virtual MembershipLevel fk_Level { get; set; }
        [InverseProperty("fk_Member")]
        public virtual AlternateAddress AlternateAddress { get; set; }
        [InverseProperty("fk_Member")]
        public virtual MemberPoint MemberPoint { get; set; }
        [InverseProperty("fk_Member")]
        public virtual ICollection<CouponSending> CouponSendings { get; set; }
        [InverseProperty("Fk_ForMemberCustomized")]
        public virtual ICollection<CustomizedOrder> CustomizedOrders { get; set; }
        [InverseProperty("fk_Booker")]
        public virtual ICollection<OneToOneReservation> OneToOneReservations { get; set; }
        [InverseProperty("fk_Member")]
        public virtual ICollection<PointHistory> PointHistories { get; set; }
        [InverseProperty("fk_Member")]
        public virtual ICollection<PointTradeIn> PointTradeIns { get; set; }
        [InverseProperty("fk_Member")]
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        [InverseProperty("fk_member")]
        public virtual ICollection<order> orders { get; set; }
    }
}