// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class MemberImg
    {
        public int Id { get; set; }
        public string ImgsPath { get; set; }
        public int fk_memberId { get; set; }

        public virtual Member IdNavigation { get; set; }
    }
}