// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class MemberPoint
    {
        public MemberPoint()
        {
            PointHistories = new HashSet<PointHistory>();
        }

        public int MemberPointsId { get; set; }
        public int PointSubtotal { get; set; }
        public int fk_MemberId { get; set; }

        public virtual Member fk_Member { get; set; }
        public virtual ICollection<PointHistory> PointHistories { get; set; }
    }
}