// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class order
    {
        public order()
        {
            PointHistories = new HashSet<PointHistory>();
            PointTradeIns = new HashSet<PointTradeIn>();
            Returns = new HashSet<Return>();
            orderItems = new HashSet<orderItem>();
        }

        public int Id { get; set; }
        public DateTime ordertime { get; set; }
        public int fk_member_Id { get; set; }
        public int total_quantity { get; set; }
        public int? logistics_company_Id { get; set; }
        public int order_status_Id { get; set; }
        public int pay_method_Id { get; set; }
        public int pay_status_Id { get; set; }
        public string coupon_name { get; set; }
        public int? coupon_discount { get; set; }
        public int? freight { get; set; }
        public string cellphone { get; set; }
        public string receipt { get; set; }
        public string receiver { get; set; }
        public string recipient_address { get; set; }
        public string order_description { get; set; }
        public int total_price { get; set; }
        public bool? close { get; set; }
        public DateTime? close_time { get; set; }
        public int? fk_typeId { get; set; }
        public string orderCode { get; set; }
        public string biller { get; set; }
        public string bill_address { get; set; }
        public string bill_cellphone { get; set; }
        public bool? agreement { get; set; }

        public virtual Member fk_member { get; set; }
        public virtual Type fk_type { get; set; }
        public virtual logistics_company logistics_company { get; set; }
        public virtual order_status order_status { get; set; }
        public virtual pay_method pay_method { get; set; }
        public virtual pay_status pay_status { get; set; }
        public virtual ICollection<PointHistory> PointHistories { get; set; }
        public virtual ICollection<PointTradeIn> PointTradeIns { get; set; }
        public virtual ICollection<Return> Returns { get; set; }
        public virtual ICollection<orderItem> orderItems { get; set; }
    }
}