// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class order
    {
        public order()
        {
            PointHistories = new HashSet<PointHistory>();
            PointTradeIns = new HashSet<PointTradeIn>();
            Returns = new HashSet<Return>();
            orderItems = new HashSet<orderItem>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ordertime { get; set; }
        public int fk_member_Id { get; set; }
        public int total_quantity { get; set; }
        public int logistics_company_Id { get; set; }
        public int order_status_Id { get; set; }
        public int pay_method_Id { get; set; }
        public int pay_status_Id { get; set; }
        [StringLength(50)]
        public string coupon_name { get; set; }
        public int? coupon_discount { get; set; }
        public int? freight { get; set; }
        [Required]
        [StringLength(12)]
        [Unicode(false)]
        public string cellphone { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string receipt { get; set; }
        [StringLength(50)]
        public string receiver { get; set; }
        [StringLength(50)]
        public string recipient_address { get; set; }
        [StringLength(50)]
        public string order_description { get; set; }
        public int total_price { get; set; }
        public bool? close { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? close_time { get; set; }
        public int? fk_typeId { get; set; }

        [ForeignKey("fk_member_Id")]
        [InverseProperty("orders")]
        public virtual Member fk_member { get; set; }
        [ForeignKey("fk_typeId")]
        [InverseProperty("orders")]
        public virtual Type fk_type { get; set; }
        [ForeignKey("logistics_company_Id")]
        [InverseProperty("orders")]
        public virtual logistics_company logistics_company { get; set; }
        [ForeignKey("order_status_Id")]
        [InverseProperty("orders")]
        public virtual order_status order_status { get; set; }
        [ForeignKey("pay_method_Id")]
        [InverseProperty("orders")]
        public virtual pay_method pay_method { get; set; }
        [ForeignKey("pay_status_Id")]
        [InverseProperty("orders")]
        public virtual pay_status pay_status { get; set; }
        [InverseProperty("fk_Order")]
        public virtual ICollection<PointHistory> PointHistories { get; set; }
        [InverseProperty("fk_Order")]
        public virtual ICollection<PointTradeIn> PointTradeIns { get; set; }
        [InverseProperty("fk訂單Navigation")]
        public virtual ICollection<Return> Returns { get; set; }
        [InverseProperty("order")]
        public virtual ICollection<orderItem> orderItems { get; set; }
    }
}