// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class pay_status
    {
        public pay_status()
        {
            orders = new HashSet<order>();
        }

        public int Id { get; set; }
        public string pay_status1 { get; set; }

        public virtual ICollection<order> orders { get; set; }
    }
}