// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class pay_method
    {
        public pay_method()
        {
            orders = new HashSet<order>();
        }

        public int Id { get; set; }
        public string pay_method1 { get; set; }

        public virtual ICollection<order> orders { get; set; }
    }
}