// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            ProductSubCategories = new HashSet<ProductSubCategory>();
        }

        [Key]
        public int ProductCategoryId { get; set; }
        [Required]
        [StringLength(50)]
        public string ProductCategoryName { get; set; }
        public int fk_SalesCategoryId { get; set; }
        [Required]
        [StringLength(100)]
        public string CategoryPath { get; set; }

        [ForeignKey("fk_SalesCategoryId")]
        [InverseProperty("ProductCategories")]
        public virtual SalesCategory fk_SalesCategory { get; set; }
        [InverseProperty("fk_ProductCategory")]
        public virtual ICollection<ProductSubCategory> ProductSubCategories { get; set; }
    }
}