// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class ProductGroup
    {
        public ProductGroup()
        {
            CartItems = new HashSet<CartItem>();
        }

        [Key]
        public int ProductGroupId { get; set; }
        [Required]
        [StringLength(254)]
        [Unicode(false)]
        public string fk_ProductId { get; set; }
        public int fk_ColorId { get; set; }
        public int fk_SizeId { get; set; }
        public int Qty { get; set; }

        [ForeignKey("fk_ColorId")]
        [InverseProperty("ProductGroups")]
        public virtual ColorCategory fk_Color { get; set; }
        [ForeignKey("fk_ProductId")]
        [InverseProperty("ProductGroups")]
        public virtual Product fk_Product { get; set; }
        [ForeignKey("fk_SizeId")]
        [InverseProperty("ProductGroups")]
        public virtual SizeCategory fk_Size { get; set; }
        [InverseProperty("fk_Product")]
        public virtual ICollection<CartItem> CartItems { get; set; }
    }
}