// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class Product
    {
        public Product()
        {
            ProductGroups = new HashSet<ProductGroup>();
            ProductImgs = new HashSet<ProductImg>();
            ProjectTagItems = new HashSet<ProjectTagItem>();
        }

        [Key]
        [StringLength(254)]
        [Unicode(false)]
        public string ProductId { get; set; }
        [Required]
        [StringLength(254)]
        public string ProductName { get; set; }
        [Required]
        public string ProductDescription { get; set; }
        [StringLength(50)]
        public string ProductMaterial { get; set; }
        [Required]
        [StringLength(50)]
        public string ProductOrigin { get; set; }
        public int? UnitPrice { get; set; }
        public int SalesPrice { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndTime { get; set; }
        [Required]
        public bool? Status { get; set; }
        public bool LogOut { get; set; }
        [StringLength(100)]
        public string Tag { get; set; }
        public int fk_ProductSubCategoryId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EditTime { get; set; }

        [ForeignKey("fk_ProductSubCategoryId")]
        [InverseProperty("Products")]
        public virtual ProductSubCategory fk_ProductSubCategory { get; set; }
        [InverseProperty("fk_Product")]
        public virtual ICollection<ProductGroup> ProductGroups { get; set; }
        [InverseProperty("fk_Product")]
        public virtual ICollection<ProductImg> ProductImgs { get; set; }
        [InverseProperty("fk_Product")]
        public virtual ICollection<ProjectTagItem> ProjectTagItems { get; set; }
    }
}