// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class Product
    {
        public Product()
        {
            Favorites = new HashSet<Favorite>();
            ProductGroups = new HashSet<ProductGroup>();
            ProductImgs = new HashSet<ProductImg>();
            ProjectTagItems = new HashSet<ProjectTagItem>();
        }

        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductMaterial { get; set; }
        public string ProductOrigin { get; set; }
        public int? UnitPrice { get; set; }
        public int SalesPrice { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public bool? Status { get; set; }
        public bool LogOut { get; set; }
        public string Tag { get; set; }
        public int fk_ProductSubCategoryId { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime EditTime { get; set; }

        public virtual ProductSubCategory fk_ProductSubCategory { get; set; }
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<ProductGroup> ProductGroups { get; set; }
        public virtual ICollection<ProductImg> ProductImgs { get; set; }
        public virtual ICollection<ProjectTagItem> ProjectTagItems { get; set; }
    }
}