// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class ProjectTag
    {
        public ProjectTag()
        {
            Coupons = new HashSet<Coupon>();
            Discounts = new HashSet<Discount>();
        }

        public int ProjectTagId { get; set; }
        public string ProjectTagName { get; set; }
        public DateTime CreateAt { get; set; }
        public DateTime ModifiedAt { get; set; }
        public bool? Status { get; set; }

        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual ICollection<Discount> Discounts { get; set; }
    }
}