// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class ReturnReson
    {
        public ReturnReson()
        {
            Returns = new HashSet<Return>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(20)]
        public string 退貨理由 { get; set; }

        [InverseProperty("退貨理由Navigation")]
        public virtual ICollection<Return> Returns { get; set; }
    }
}