// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class SalesCategory
    {
        public SalesCategory()
        {
            ProductCategories = new HashSet<ProductCategory>();
        }

        public int SalesCategoryId { get; set; }
        public string SalesCategoryName { get; set; }

        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
    }
}