// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class ShoesOrder
    {
        public ShoesOrder()
        {
            ShoesGroups = new HashSet<ShoesGroup>();
        }

        [Key]
        public int ShoesOrderId { get; set; }
        public int Qty { get; set; }
        public int fk_ShoesSizeId { get; set; }
        [StringLength(300)]
        public string Remark { get; set; }

        [ForeignKey("fk_ShoesSizeId")]
        [InverseProperty("ShoesOrders")]
        public virtual ShoesSize fk_ShoesSize { get; set; }
        [InverseProperty("fk_CustomerOrder")]
        public virtual ICollection<ShoesGroup> ShoesGroups { get; set; }
    }
}