// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModels.Models
{
    public partial class ShoesOrder
    {
        public ShoesOrder()
        {
            ShoesGroups = new HashSet<ShoesGroup>();
        }

        public string ShoesOrderId { get; set; }
        public int Qty { get; set; }
        public int fk_ShoesSizeId { get; set; }
        public string Remark { get; set; }

        public virtual ShoesSize fk_ShoesSize { get; set; }
        public virtual ICollection<ShoesGroup> ShoesGroups { get; set; }
    }
}