// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class SpeakerField
    {
        public SpeakerField()
        {
            Speakers = new HashSet<Speaker>();
        }

        [Key]
        public int FieldId { get; set; }
        [Required]
        [StringLength(50)]
        public string FieldName { get; set; }

        [InverseProperty("fk_SpeakerField")]
        public virtual ICollection<Speaker> Speakers { get; set; }
    }
}