// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class Speaker
    {
        public Speaker()
        {
            Activities = new HashSet<Activity>();
            OneToOneReservations = new HashSet<OneToOneReservation>();
        }

        [Key]
        public int SpeakerId { get; set; }
        [Required]
        [StringLength(50)]
        public string SpeakerName { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string SpeakerPhone { get; set; }
        public int fk_SpeakerFieldId { get; set; }
        [StringLength(300)]
        [Unicode(false)]
        public string SpeakerImg { get; set; }
        public int? fk_SpeakerBranchId { get; set; }
        [StringLength(500)]
        public string SpeakerDescription { get; set; }
        public bool SpeakerVisible { get; set; }

        [ForeignKey("fk_SpeakerBranchId")]
        [InverseProperty("Speakers")]
        public virtual Branch fk_SpeakerBranch { get; set; }
        [ForeignKey("fk_SpeakerFieldId")]
        [InverseProperty("Speakers")]
        public virtual SpeakerField fk_SpeakerField { get; set; }
        [InverseProperty("fk_Speaker")]
        public virtual ICollection<Activity> Activities { get; set; }
        [InverseProperty("fk_ReservationSpeaker")]
        public virtual ICollection<OneToOneReservation> OneToOneReservations { get; set; }
    }
}