// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class Staff
    {
        [Key]
        public int StaffId { get; set; }
        [Required]
        [StringLength(30)]
        public string Name { get; set; }
        public byte? Age { get; set; }
        public bool? Gender { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Mobile { get; set; }
        [Required]
        [StringLength(300)]
        public string Email { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Birthday { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string Account { get; set; }
        [Required]
        [StringLength(70)]
        [Unicode(false)]
        public string Password { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DueDate { get; set; }
        public int fk_PermissionsId { get; set; }
        public int fk_TitleId { get; set; }
        public int fk_DepartmentId { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string ConfirmCode { get; set; }

        [ForeignKey("fk_DepartmentId")]
        [InverseProperty("Staff")]
        public virtual Department fk_Department { get; set; }
        [ForeignKey("fk_PermissionsId")]
        [InverseProperty("Staff")]
        public virtual StaffPermission fk_Permissions { get; set; }
        [ForeignKey("fk_TitleId")]
        [InverseProperty("Staff")]
        public virtual JobTitle fk_Title { get; set; }
    }
}