// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class ActivityCategory
    {
        public ActivityCategory()
        {
            Activities = new HashSet<Activity>();
        }

        public int ActivityCategoryId { get; set; }
        public string ActivityCategoryName { get; set; }

        public virtual ICollection<Activity> Activities { get; set; }
    }
}