// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class BlackList
    {
        public BlackList()
        {
            Members = new HashSet<Member>();
        }

        public int BlackListId { get; set; }
        public string Behavior { get; set; }
        public DateTime? CreatedAt { get; set; }

        public virtual ICollection<Member> Members { get; set; }
    }
}