// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class CouponSending
    {
        public int SendingId { get; set; }
        public int fk_CouponId { get; set; }
        public int? fk_MemberId { get; set; }
        public DateTime SentDate { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool RedemptionStatus { get; set; }
        public DateTime? RedeemedDate { get; set; }

        public virtual Coupon fk_Coupon { get; set; }
        public virtual Member fk_Member { get; set; }
    }
}