// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class Discount
    {
        public int DiscountId { get; set; }
        public string DiscountName { get; set; }
        public string DiscountDescription { get; set; }
        public int? fk_ProjectTagId { get; set; }
        public int DiscountType { get; set; }
        public int DiscountValue { get; set; }
        public int ConditionType { get; set; }
        public int ConditionValue { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int? OrderBy { get; set; }
        public bool? Status { get; set; }

        public virtual ProjectTag fk_ProjectTag { get; set; }
    }
}