// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class OneToOneReservation
    {
        public int ReservationId { get; set; }
        public int fk_BookerId { get; set; }
        public DateTime ReservationStartTime { get; set; }
        public DateTime ReservationEndTime { get; set; }
        public int fk_BranchId { get; set; }
        public int fk_ReservationSpeakerId { get; set; }
        public int fk_ReservationStatusId { get; set; }
        public DateTime ReservationCreatedDate { get; set; }

        public virtual Member fk_Booker { get; set; }
        public virtual Branch fk_Branch { get; set; }
        public virtual Speaker fk_ReservationSpeaker { get; set; }
        public virtual ReservationStatus fk_ReservationStatus { get; set; }
    }
}