// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class ProductSubCategory
    {
        public ProductSubCategory()
        {
            Products = new HashSet<Product>();
        }

        public int ProductSubCategoryId { get; set; }
        public string ProductSubCategoryName { get; set; }
        public int fk_ProductCategoryId { get; set; }
        public string SubCategoryPath { get; set; }

        public virtual ProductCategory fk_ProductCategory { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}