// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class ProductImg
    {
        public int ProductImgId { get; set; }
        public string fk_ProductId { get; set; }
        public int? fk_ColorId { get; set; }
        public string ImgPath { get; set; }

        public virtual ColorCategory fk_Color { get; set; }
        public virtual Product fk_Product { get; set; }
    }
}