// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            ProductSubCategories = new HashSet<ProductSubCategory>();
        }

        public int ProductCategoryId { get; set; }
        public string ProductCategoryName { get; set; }
        public int fk_SalesCategoryId { get; set; }
        public string CategoryPath { get; set; }

        public virtual SalesCategory fk_SalesCategory { get; set; }
        public virtual ICollection<ProductSubCategory> ProductSubCategories { get; set; }
    }
}