// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class ReturnReson
    {
        public ReturnReson()
        {
            Returns = new HashSet<Return>();
        }

        public int ID { get; set; }
        public string 退貨理由 { get; set; }

        public virtual ICollection<Return> Returns { get; set; }
    }
}