// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            CartItems = new HashSet<CartItem>();
        }

        public int CartId { get; set; }
        public int fk_MemberID { get; set; }
        public string CartItemsId { get; set; }
        public bool? Status { get; set; }

        public virtual Member fk_Member { get; set; }
        public virtual ICollection<CartItem> CartItems { get; set; }
    }
}