// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class StaffPermission
    {
        public StaffPermission()
        {
            Staff = new HashSet<Staff>();
        }

        public int PermissionsId { get; set; }
        public string LevelName { get; set; }

        public virtual ICollection<Staff> Staff { get; set; }
    }
}