// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCoreService.Models.EFModels
{
    public partial class Supplier
    {
        public int SupplierId { get; set; }
        public string SupplierCompanyName { get; set; }
        public bool? HasCertificate { get; set; }
        public string Supply_Material { get; set; }
        public int? SupplierCompanyPhone { get; set; }
        public string SupplierCompanyEmail { get; set; }
        public string SupplierCompanyAddress { get; set; }
        public int? SupplierCompanyNumber { get; set; }
        public DateTime? SupplierStartDate { get; set; }
    }
}